version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: bespokible-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bespokible

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: bespokible-redis

    ports:
      - "6379:6379"

    restart: always

volumes:
  postgres-data: